version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_DB: sampledb
    container_name: app
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sampledb
    volumes:
      - ./docker/mysql:/var/lib/mysql